--- 
title: "A Minimal Book Example"
author: "Yihui Xie"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "ww"
---

# Algebra en $\mathbb{R}$
Sea $a\in\mathcal{R}$ entonces la relacion de este con $t$ es similar a el desden de continuar con los resultados falaces.

 
 
 $$\frac{w}{\rho^2_r=t^3-r\omega_1^3}=\sqrt{\frac{r}{r^7}}=\int_{\ln  3}^{\ln n}$$
           $$$$
 
 $$$$
 
```{r eval=FALSE}
install.packages("bookdown")
# or the development version
# devtools::install_github("rstudio/bookdown")
```

Remember each Rmd file contains one and only one chapter, and a chapter is defined by the first-level heading `#`.

To compile this example to PDF, you need XeLaTeX. You are recommended to install TinyTeX (which includes XeLaTeX): <https://yihui.org/tinytex/>.

```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```
